# Generated by Django 3.1.4 on 2020-12-02 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('iso_code', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=150)),
                ('kind', models.CharField(max_length=250)),
                ('dimension', models.CharField(max_length=2000)),
                ('image', models.CharField(max_length=1500)),
                ('category', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='products.category')),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='products.country')),
            ],
            options={
                'db_table': 'state',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('sample_delivery', models.BooleanField(default=False)),
                ('virtual_assistance', models.BooleanField(default=False)),
                ('open_slot', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('image', models.TextField(max_length=2000)),
                ('ratings', models.IntegerField()),
                ('country', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='products.country')),
                ('state', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='products.state')),
            ],
            options={
                'db_table': 'vendors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='products.products')),
                ('vendor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='products.vendors')),
            ],
            options={
                'db_table': 'stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='products.products')),
                ('vendor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='products.vendors')),
            ],
            options={
                'db_table': 'rating',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='products.vendors'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('country', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='products.country')),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='products.products')),
                ('state', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='products.state')),
                ('vendor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='products.vendors')),
            ],
            options={
                'db_table': 'price',
                'managed': True,
            },
        ),
    ]
