# Generated by Django 3.1.4 on 2020-12-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201204_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='store_kind',
            field=models.TextField(default='Furniture store', max_length=500),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='open_slot',
            field=models.TextField(default='9:00AM - 6:00PM', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='ratings',
            field=models.IntegerField(default=4),
        ),
    ]
