# Generated by Django 3.1.4 on 2020-12-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201204_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='added_to_cart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
