# Generated by Django 3.1.4 on 2020-12-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201205_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(default='Furniture Store', max_length=200),
        ),
    ]
