# Generated by Django 3.1.4 on 2020-12-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201205_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prices',
            field=models.IntegerField(default=30000),
        ),
    ]
