# Generated by Django 3.1.4 on 2020-12-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sku',
            field=models.CharField(default='SF2SMD0012S0003', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='dimension',
            field=models.CharField(default='45 X 64 X 90', max_length=2000),
        ),
    ]
