# Generated by Django 3.1.4 on 2020-12-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201205_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cart_item_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
