# Generated by Django 3.1.4 on 2020-12-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201205_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='added_to_cart',
        ),
    ]
